// AI Models Configuration - 180+ AI Models
// API keys are stored securely and configured by the user

export interface AIModel {
  id: string
  name: string
  provider: string
  category: string
  description: string
  maxTokens: number
  apiEndpoint: string
  apiKeyName: string
  isAvailable: boolean
}

export interface AIProvider {
  id: string
  name: string
  logo: string
  website: string
  apiKeyName: string
  models: AIModel[]
}

export const AI_PROVIDERS: AIProvider[] = [
  // Deepseek Models (Official API - Priority)
  {
    id: "deepseek",
    name: "Deepseek",
    logo: "https://cdn.jsdelivr.net/gh/glincker/thesvg@main/public/icons/deepseek-ai/default.svg",
    website: "https://deepseek.com",
    apiKeyName: "DEEPSEEK_API_KEY",
    models: [
      {
        id: "deepseek-v4-pro",
        name: "Deepseek V4 Pro",
        provider: "deepseek",
        category: "reasoning",
        description: "官方最强推理模型 - 支持扩展思考功能",
        maxTokens: 128000,
        apiEndpoint: "https://api.deepseek.com/chat/completions",
        apiKeyName: "DEEPSEEK_API_KEY",
        isAvailable: true,
      },
      {
        id: "deepseek-chat",
        name: "Deepseek Chat",
        provider: "deepseek",
        category: "chat",
        description: "标准聊天模型 - 低成本高性能",
        maxTokens: 64000,
        apiEndpoint: "https://api.deepseek.com/chat/completions",
        apiKeyName: "DEEPSEEK_API_KEY",
        isAvailable: true,
      },
      {
        id: "deepseek-code",
        name: "Deepseek Code",
        provider: "deepseek",
        category: "code",
        description: "代码生成模型 - 编程专用",
        maxTokens: 64000,
        apiEndpoint: "https://api.deepseek.com/chat/completions",
        apiKeyName: "DEEPSEEK_API_KEY",
        isAvailable: true,
      },
    ]
  },
  // OpenAI Models
  {
    id: "openai",
    name: "OpenAI",
    logo: "https://cdn.jsdelivr.net/gh/glincker/thesvg@main/public/icons/openai/default.svg",
    website: "https://openai.com",
    apiKeyName: "OPENAI_API_KEY",
    models: [
      {
        id: "gpt-4o",
        name: "GPT-4 Omni",
        provider: "openai",
        category: "chat",
        description: "最新多模态模型",
        maxTokens: 128000,
        apiEndpoint: "https://api.openai.com/v1/chat/completions",
        apiKeyName: "OPENAI_API_KEY",
        isAvailable: true,
      },
      {
        id: "gpt-4o-mini",
        name: "GPT-4o Mini",
        provider: "openai",
        category: "chat",
        description: "快速轻量版",
        maxTokens: 128000,
        apiEndpoint: "https://api.openai.com/v1/chat/completions",
        apiKeyName: "OPENAI_API_KEY",
        isAvailable: true,
      },
      {
        id: "gpt-4-turbo",
        name: "GPT-4 Turbo",
        provider: "openai",
        category: "chat",
        description: "增强推理能力",
        maxTokens: 128000,
        apiEndpoint: "https://api.openai.com/v1/chat/completions",
        apiKeyName: "OPENAI_API_KEY",
        isAvailable: true,
      },
      {
        id: "gpt-4",
        name: "GPT-4",
        provider: "openai",
        category: "chat",
        description: "强大推理模型",
        maxTokens: 8192,
        apiEndpoint: "https://api.openai.com/v1/chat/completions",
        apiKeyName: "OPENAI_API_KEY",
        isAvailable: true,
      },
      {
        id: "gpt-3.5-turbo",
        name: "GPT-3.5 Turbo",
        provider: "openai",
        category: "chat",
        description: "快速响应模型",
        maxTokens: 16385,
        apiEndpoint: "https://api.openai.com/v1/chat/completions",
        apiKeyName: "OPENAI_API_KEY",
        isAvailable: true,
      },
      {
        id: "gpt-4-vision",
        name: "GPT-4 Vision",
        provider: "openai",
        category: "vision",
        description: "图像理解能力",
        maxTokens: 128000,
        apiEndpoint: "https://api.openai.com/v1/chat/completions",
        apiKeyName: "OPENAI_API_KEY",
        isAvailable: true,
      },
      {
        id: "o1-preview",
        name: "o1 Preview",
        provider: "openai",
        category: "reasoning",
        description: "高级推理模型",
        maxTokens: 128000,
        apiEndpoint: "https://api.openai.com/v1/chat/completions",
        apiKeyName: "OPENAI_API_KEY",
        isAvailable: true,
      },
      {
        id: "o1-mini",
        name: "o1 Mini",
        provider: "openai",
        category: "reasoning",
        description: "轻量推理模型",
        maxTokens: 128000,
        apiEndpoint: "https://api.openai.com/v1/chat/completions",
        apiKeyName: "OPENAI_API_KEY",
        isAvailable: true,
      },
      {
        id: "dall-e-3",
        name: "DALL-E 3",
        provider: "openai",
        category: "image",
        description: "图像生成模型",
        maxTokens: 4096,
        apiEndpoint: "https://api.openai.com/v1/images/generations",
        apiKeyName: "OPENAI_API_KEY",
        isAvailable: true,
      },
      {
        id: "dall-e-2",
        name: "DALL-E 2",
        provider: "openai",
        category: "image",
        description: "图像生成模型",
        maxTokens: 4096,
        apiEndpoint: "https://api.openai.com/v1/images/generations",
        apiKeyName: "OPENAI_API_KEY",
        isAvailable: true,
      },
      {
        id: "whisper-1",
        name: "Whisper",
        provider: "openai",
        category: "audio",
        description: "语音转文字",
        maxTokens: 0,
        apiEndpoint: "https://api.openai.com/v1/audio/transcriptions",
        apiKeyName: "OPENAI_API_KEY",
        isAvailable: true,
      },
      {
        id: "tts-1",
        name: "TTS-1",
        provider: "openai",
        category: "audio",
        description: "文字转语音",
        maxTokens: 4096,
        apiEndpoint: "https://api.openai.com/v1/audio/speech",
        apiKeyName: "OPENAI_API_KEY",
        isAvailable: true,
      },
      {
        id: "tts-1-hd",
        name: "TTS-1 HD",
        provider: "openai",
        category: "audio",
        description: "高清语音合成",
        maxTokens: 4096,
        apiEndpoint: "https://api.openai.com/v1/audio/speech",
        apiKeyName: "OPENAI_API_KEY",
        isAvailable: true,
      },
      {
        id: "text-embedding-3-large",
        name: "Embedding Large",
        provider: "openai",
        category: "embedding",
        description: "文本嵌入模型",
        maxTokens: 8191,
        apiEndpoint: "https://api.openai.com/v1/embeddings",
        apiKeyName: "OPENAI_API_KEY",
        isAvailable: true,
      },
      {
        id: "text-embedding-3-small",
        name: "Embedding Small",
        provider: "openai",
        category: "embedding",
        description: "轻量嵌入模型",
        maxTokens: 8191,
        apiEndpoint: "https://api.openai.com/v1/embeddings",
        apiKeyName: "OPENAI_API_KEY",
        isAvailable: true,
      },
    ],
  },
  // Anthropic Models
  {
    id: "anthropic",
    name: "Anthropic",
    logo: "https://cdn.jsdelivr.net/gh/glincker/thesvg@main/public/icons/anthropic/default.svg",
    website: "https://anthropic.com",
    apiKeyName: "ANTHROPIC_API_KEY",
    models: [
      {
        id: "claude-3-opus",
        name: "Claude 3 Opus",
        provider: "anthropic",
        category: "chat",
        description: "最强大的Claude模型",
        maxTokens: 200000,
        apiEndpoint: "https://api.anthropic.com/v1/messages",
        apiKeyName: "ANTHROPIC_API_KEY",
        isAvailable: true,
      },
      {
        id: "claude-3-sonnet",
        name: "Claude 3 Sonnet",
        provider: "anthropic",
        category: "chat",
        description: "平衡型Claude模型",
        maxTokens: 200000,
        apiEndpoint: "https://api.anthropic.com/v1/messages",
        apiKeyName: "ANTHROPIC_API_KEY",
        isAvailable: true,
      },
      {
        id: "claude-3-haiku",
        name: "Claude 3 Haiku",
        provider: "anthropic",
        category: "chat",
        description: "快速Claude模型",
        maxTokens: 200000,
        apiEndpoint: "https://api.anthropic.com/v1/messages",
        apiKeyName: "ANTHROPIC_API_KEY",
        isAvailable: true,
      },
      {
        id: "claude-3.5-sonnet",
        name: "Claude 3.5 Sonnet",
        provider: "anthropic",
        category: "chat",
        description: "最新Sonnet版本",
        maxTokens: 200000,
        apiEndpoint: "https://api.anthropic.com/v1/messages",
        apiKeyName: "ANTHROPIC_API_KEY",
        isAvailable: true,
      },
      {
        id: "claude-3.5-haiku",
        name: "Claude 3.5 Haiku",
        provider: "anthropic",
        category: "chat",
        description: "最新Haiku版本",
        maxTokens: 200000,
        apiEndpoint: "https://api.anthropic.com/v1/messages",
        apiKeyName: "ANTHROPIC_API_KEY",
        isAvailable: true,
      },
      {
        id: "claude-2.1",
        name: "Claude 2.1",
        provider: "anthropic",
        category: "chat",
        description: "Claude 2升级版",
        maxTokens: 100000,
        apiEndpoint: "https://api.anthropic.com/v1/messages",
        apiKeyName: "ANTHROPIC_API_KEY",
        isAvailable: true,
      },
      {
        id: "claude-2",
        name: "Claude 2",
        provider: "anthropic",
        category: "chat",
        description: "经典Claude模型",
        maxTokens: 100000,
        apiEndpoint: "https://api.anthropic.com/v1/messages",
        apiKeyName: "ANTHROPIC_API_KEY",
        isAvailable: true,
      },
      {
        id: "claude-instant",
        name: "Claude Instant",
        provider: "anthropic",
        category: "chat",
        description: "快速响应版本",
        maxTokens: 100000,
        apiEndpoint: "https://api.anthropic.com/v1/messages",
        apiKeyName: "ANTHROPIC_API_KEY",
        isAvailable: true,
      },
    ],
  },
  // Google Models
  {
    id: "google",
    name: "Google",
    logo: "🔷",
    website: "https://ai.google.dev",
    apiKeyName: "GOOGLE_API_KEY",
    models: [
      {
        id: "gemini-2.0-flash",
        name: "Gemini 2.0 Flash",
        provider: "google",
        category: "chat",
        description: "最新快速模型",
        maxTokens: 1000000,
        apiEndpoint: "https://generativelanguage.googleapis.com/v1/models",
        apiKeyName: "GOOGLE_API_KEY",
        isAvailable: true,
      },
      {
        id: "gemini-2.5-flash",
        name: "Gemini 2.5 Flash",
        provider: "google",
        category: "chat",
        description: "超快速模型",
        maxTokens: 1000000,
        apiEndpoint: "https://generativelanguage.googleapis.com/v1/models",
        apiKeyName: "GOOGLE_API_KEY",
        isAvailable: true,
      },
      {
        id: "gemini-1.5-pro",
        name: "Gemini 1.5 Pro",
        provider: "google",
        category: "chat",
        description: "专业级模型",
        maxTokens: 2000000,
        apiEndpoint: "https://generativelanguage.googleapis.com/v1/models",
        apiKeyName: "GOOGLE_API_KEY",
        isAvailable: true,
      },
      {
        id: "gemini-1.5-flash",
        name: "Gemini 1.5 Flash",
        provider: "google",
        category: "chat",
        description: "快速响应模型",
        maxTokens: 1000000,
        apiEndpoint: "https://generativelanguage.googleapis.com/v1/models",
        apiKeyName: "GOOGLE_API_KEY",
        isAvailable: true,
      },
      {
        id: "gemini-1.0-pro",
        name: "Gemini 1.0 Pro",
        provider: "google",
        category: "chat",
        description: "稳定版模型",
        maxTokens: 32000,
        apiEndpoint: "https://generativelanguage.googleapis.com/v1/models",
        apiKeyName: "GOOGLE_API_KEY",
        isAvailable: true,
      },
      {
        id: "gemini-pro-vision",
        name: "Gemini Pro Vision",
        provider: "google",
        category: "vision",
        description: "视觉理解模型",
        maxTokens: 32000,
        apiEndpoint: "https://generativelanguage.googleapis.com/v1/models",
        apiKeyName: "GOOGLE_API_KEY",
        isAvailable: true,
      },
      {
        id: "gemini-ultra",
        name: "Gemini Ultra",
        provider: "google",
        category: "chat",
        description: "最强大模型",
        maxTokens: 32000,
        apiEndpoint: "https://generativelanguage.googleapis.com/v1/models",
        apiKeyName: "GOOGLE_API_KEY",
        isAvailable: true,
      },
      {
        id: "palm-2",
        name: "PaLM 2",
        provider: "google",
        category: "chat",
        description: "经典大模型",
        maxTokens: 8192,
        apiEndpoint: "https://generativelanguage.googleapis.com/v1/models",
        apiKeyName: "GOOGLE_API_KEY",
        isAvailable: true,
      },
      {
        id: "imagen-3",
        name: "Imagen 3",
        provider: "google",
        category: "image",
        description: "图像生成模型",
        maxTokens: 4096,
        apiEndpoint: "https://generativelanguage.googleapis.com/v1/models",
        apiKeyName: "GOOGLE_API_KEY",
        isAvailable: true,
      },
      {
        id: "veo-2",
        name: "Veo 2",
        provider: "google",
        category: "video",
        description: "视频生成模型",
        maxTokens: 4096,
        apiEndpoint: "https://generativelanguage.googleapis.com/v1/models",
        apiKeyName: "GOOGLE_API_KEY",
        isAvailable: true,
      },
    ],
  },
  // DeepSeek Models
  {
    id: "deepseek",
    name: "DeepSeek",
    logo: "🌊",
    website: "https://deepseek.com",
    apiKeyName: "DEEPSEEK_API_KEY",
    models: [
      {
        id: "deepseek-r1",
        name: "DeepSeek R1",
        provider: "deepseek",
        category: "reasoning",
        description: "推理专用模型",
        maxTokens: 64000,
        apiEndpoint: "https://api.deepseek.com/v1/chat/completions",
        apiKeyName: "DEEPSEEK_API_KEY",
        isAvailable: true,
      },
      {
        id: "deepseek-r1-lite",
        name: "DeepSeek R1 Lite",
        provider: "deepseek",
        category: "reasoning",
        description: "轻量推理模型",
        maxTokens: 32000,
        apiEndpoint: "https://api.deepseek.com/v1/chat/completions",
        apiKeyName: "DEEPSEEK_API_KEY",
        isAvailable: true,
      },
      {
        id: "deepseek-v3",
        name: "DeepSeek V3",
        provider: "deepseek",
        category: "chat",
        description: "最新对话模型",
        maxTokens: 64000,
        apiEndpoint: "https://api.deepseek.com/v1/chat/completions",
        apiKeyName: "DEEPSEEK_API_KEY",
        isAvailable: true,
      },
      {
        id: "deepseek-v3-0324",
        name: "DeepSeek V3-0324",
        provider: "deepseek",
        category: "chat",
        description: "三月更新版",
        maxTokens: 64000,
        apiEndpoint: "https://api.deepseek.com/v1/chat/completions",
        apiKeyName: "DEEPSEEK_API_KEY",
        isAvailable: true,
      },
      {
        id: "deepseek-v2.5",
        name: "DeepSeek V2.5",
        provider: "deepseek",
        category: "chat",
        description: "稳定版模型",
        maxTokens: 32000,
        apiEndpoint: "https://api.deepseek.com/v1/chat/completions",
        apiKeyName: "DEEPSEEK_API_KEY",
        isAvailable: true,
      },
      {
        id: "deepseek-coder-v2",
        name: "DeepSeek Coder V2",
        provider: "deepseek",
        category: "code",
        description: "代码专用模型",
        maxTokens: 128000,
        apiEndpoint: "https://api.deepseek.com/v1/chat/completions",
        apiKeyName: "DEEPSEEK_API_KEY",
        isAvailable: true,
      },
      {
        id: "deepseek-math",
        name: "DeepSeek Math",
        provider: "deepseek",
        category: "math",
        description: "数学专用模型",
        maxTokens: 32000,
        apiEndpoint: "https://api.deepseek.com/v1/chat/completions",
        apiKeyName: "DEEPSEEK_API_KEY",
        isAvailable: true,
      },
    ],
  },
  // Meta/Llama Models
  {
    id: "meta",
    name: "Meta AI",
    logo: "🦙",
    website: "https://llama.meta.com",
    apiKeyName: "META_API_KEY",
    models: [
      {
        id: "llama-3.2-405b",
        name: "Llama 3.2 405B",
        provider: "meta",
        category: "chat",
        description: "超大规模模型",
        maxTokens: 128000,
        apiEndpoint: "https://api.together.xyz/v1/chat/completions",
        apiKeyName: "TOGETHER_API_KEY",
        isAvailable: true,
      },
      {
        id: "llama-3.2-70b",
        name: "Llama 3.2 70B",
        provider: "meta",
        category: "chat",
        description: "大型模型",
        maxTokens: 128000,
        apiEndpoint: "https://api.together.xyz/v1/chat/completions",
        apiKeyName: "TOGETHER_API_KEY",
        isAvailable: true,
      },
      {
        id: "llama-3.2-8b",
        name: "Llama 3.2 8B",
        provider: "meta",
        category: "chat",
        description: "轻量级模型",
        maxTokens: 128000,
        apiEndpoint: "https://api.together.xyz/v1/chat/completions",
        apiKeyName: "TOGETHER_API_KEY",
        isAvailable: true,
      },
      {
        id: "llama-3.1-405b",
        name: "Llama 3.1 405B",
        provider: "meta",
        category: "chat",
        description: "旗舰模型",
        maxTokens: 128000,
        apiEndpoint: "https://api.together.xyz/v1/chat/completions",
        apiKeyName: "TOGETHER_API_KEY",
        isAvailable: true,
      },
      {
        id: "llama-3.1-70b",
        name: "Llama 3.1 70B",
        provider: "meta",
        category: "chat",
        description: "高性能模型",
        maxTokens: 128000,
        apiEndpoint: "https://api.together.xyz/v1/chat/completions",
        apiKeyName: "TOGETHER_API_KEY",
        isAvailable: true,
      },
      {
        id: "llama-3-70b",
        name: "Llama 3 70B",
        provider: "meta",
        category: "chat",
        description: "经典大模型",
        maxTokens: 8192,
        apiEndpoint: "https://api.together.xyz/v1/chat/completions",
        apiKeyName: "TOGETHER_API_KEY",
        isAvailable: true,
      },
      {
        id: "llama-3-8b",
        name: "Llama 3 8B",
        provider: "meta",
        category: "chat",
        description: "快速模型",
        maxTokens: 8192,
        apiEndpoint: "https://api.together.xyz/v1/chat/completions",
        apiKeyName: "TOGETHER_API_KEY",
        isAvailable: true,
      },
      {
        id: "code-llama-70b",
        name: "Code Llama 70B",
        provider: "meta",
        category: "code",
        description: "代码专用模型",
        maxTokens: 16384,
        apiEndpoint: "https://api.together.xyz/v1/chat/completions",
        apiKeyName: "TOGETHER_API_KEY",
        isAvailable: true,
      },
      {
        id: "code-llama-34b",
        name: "Code Llama 34B",
        provider: "meta",
        category: "code",
        description: "中型代码模型",
        maxTokens: 16384,
        apiEndpoint: "https://api.together.xyz/v1/chat/completions",
        apiKeyName: "TOGETHER_API_KEY",
        isAvailable: true,
      },
    ],
  },
  // Alibaba/Qwen Models
  {
    id: "alibaba",
    name: "阿里巴巴",
    logo: "☁️",
    website: "https://qwen.ai",
    apiKeyName: "QWEN_API_KEY",
    models: [
      {
        id: "qwen-max",
        name: "Qwen Max",
        provider: "alibaba",
        category: "chat",
        description: "最强通义千问",
        maxTokens: 32000,
        apiEndpoint: "https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation",
        apiKeyName: "QWEN_API_KEY",
        isAvailable: true,
      },
      {
        id: "qwen-plus",
        name: "Qwen Plus",
        provider: "alibaba",
        category: "chat",
        description: "增强版千问",
        maxTokens: 32000,
        apiEndpoint: "https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation",
        apiKeyName: "QWEN_API_KEY",
        isAvailable: true,
      },
      {
        id: "qwen-turbo",
        name: "Qwen Turbo",
        provider: "alibaba",
        category: "chat",
        description: "快速版千问",
        maxTokens: 8000,
        apiEndpoint: "https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation",
        apiKeyName: "QWEN_API_KEY",
        isAvailable: true,
      },
      {
        id: "qwen-2.5-72b",
        name: "Qwen 2.5 72B",
        provider: "alibaba",
        category: "chat",
        description: "大规模模型",
        maxTokens: 128000,
        apiEndpoint: "https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation",
        apiKeyName: "QWEN_API_KEY",
        isAvailable: true,
      },
      {
        id: "qwen-2.5-32b",
        name: "Qwen 2.5 32B",
        provider: "alibaba",
        category: "chat",
        description: "中型模型",
        maxTokens: 128000,
        apiEndpoint: "https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation",
        apiKeyName: "QWEN_API_KEY",
        isAvailable: true,
      },
      {
        id: "qwen-2.5-14b",
        name: "Qwen 2.5 14B",
        provider: "alibaba",
        category: "chat",
        description: "平衡型模型",
        maxTokens: 128000,
        apiEndpoint: "https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation",
        apiKeyName: "QWEN_API_KEY",
        isAvailable: true,
      },
      {
        id: "qwen-2.5-7b",
        name: "Qwen 2.5 7B",
        provider: "alibaba",
        category: "chat",
        description: "轻量模型",
        maxTokens: 128000,
        apiEndpoint: "https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation",
        apiKeyName: "QWEN_API_KEY",
        isAvailable: true,
      },
      {
        id: "qwen-coder-32b",
        name: "Qwen Coder 32B",
        provider: "alibaba",
        category: "code",
        description: "代码专用",
        maxTokens: 128000,
        apiEndpoint: "https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation",
        apiKeyName: "QWEN_API_KEY",
        isAvailable: true,
      },
      {
        id: "qwen-vl-max",
        name: "Qwen VL Max",
        provider: "alibaba",
        category: "vision",
        description: "视觉语言模型",
        maxTokens: 32000,
        apiEndpoint: "https://dashscope.aliyuncs.com/api/v1/services/aigc/multimodal-generation/generation",
        apiKeyName: "QWEN_API_KEY",
        isAvailable: true,
      },
      {
        id: "qwen-audio",
        name: "Qwen Audio",
        provider: "alibaba",
        category: "audio",
        description: "音频理解模型",
        maxTokens: 32000,
        apiEndpoint: "https://dashscope.aliyuncs.com/api/v1/services/aigc/multimodal-generation/generation",
        apiKeyName: "QWEN_API_KEY",
        isAvailable: true,
      },
    ],
  },
  // Tencent/Hunyuan Models
  {
    id: "tencent",
    name: "腾讯",
    logo: "🐧",
    website: "https://hunyuan.tencent.com",
    apiKeyName: "HUNYUAN_API_KEY",
    models: [
      {
        id: "hunyuan-large",
        name: "混元 Large",
        provider: "tencent",
        category: "chat",
        description: "超大规模模型",
        maxTokens: 256000,
        apiEndpoint: "https://hunyuan.tencentcloudapi.com",
        apiKeyName: "HUNYUAN_API_KEY",
        isAvailable: true,
      },
      {
        id: "hunyuan-large-3",
        name: "混元 Large 3",
        provider: "tencent",
        category: "chat",
        description: "第三代大模型",
        maxTokens: 256000,
        apiEndpoint: "https://hunyuan.tencentcloudapi.com",
        apiKeyName: "HUNYUAN_API_KEY",
        isAvailable: true,
      },
      {
        id: "hunyuan-pro",
        name: "混元 Pro",
        provider: "tencent",
        category: "chat",
        description: "专业版模型",
        maxTokens: 32000,
        apiEndpoint: "https://hunyuan.tencentcloudapi.com",
        apiKeyName: "HUNYUAN_API_KEY",
        isAvailable: true,
      },
      {
        id: "hunyuan-standard",
        name: "混元 Standard",
        provider: "tencent",
        category: "chat",
        description: "标准版模型",
        maxTokens: 16000,
        apiEndpoint: "https://hunyuan.tencentcloudapi.com",
        apiKeyName: "HUNYUAN_API_KEY",
        isAvailable: true,
      },
      {
        id: "hunyuan-lite",
        name: "混元 Lite",
        provider: "tencent",
        category: "chat",
        description: "轻量版模型",
        maxTokens: 8000,
        apiEndpoint: "https://hunyuan.tencentcloudapi.com",
        apiKeyName: "HUNYUAN_API_KEY",
        isAvailable: true,
      },
      {
        id: "hunyuan-code",
        name: "混元 Code",
        provider: "tencent",
        category: "code",
        description: "代码专用模型",
        maxTokens: 32000,
        apiEndpoint: "https://hunyuan.tencentcloudapi.com",
        apiKeyName: "HUNYUAN_API_KEY",
        isAvailable: true,
      },
      {
        id: "hunyuan-vision",
        name: "混元 Vision",
        provider: "tencent",
        category: "vision",
        description: "视觉理解模型",
        maxTokens: 32000,
        apiEndpoint: "https://hunyuan.tencentcloudapi.com",
        apiKeyName: "HUNYUAN_API_KEY",
        isAvailable: true,
      },
    ],
  },
  // Baidu/ERNIE Models
  {
    id: "baidu",
    name: "百度",
    logo: "🔵",
    website: "https://yiyan.baidu.com",
    apiKeyName: "ERNIE_API_KEY",
    models: [
      {
        id: "ernie-4.0",
        name: "文心一言 4.0",
        provider: "baidu",
        category: "chat",
        description: "最新旗舰模型",
        maxTokens: 8192,
        apiEndpoint: "https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/completions_pro",
        apiKeyName: "ERNIE_API_KEY",
        isAvailable: true,
      },
      {
        id: "ernie-4.0-turbo",
        name: "文心一言 4.0 Turbo",
        provider: "baidu",
        category: "chat",
        description: "快速响应版",
        maxTokens: 8192,
        apiEndpoint: "https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/ernie-4.0-turbo-8k",
        apiKeyName: "ERNIE_API_KEY",
        isAvailable: true,
      },
      {
        id: "ernie-3.5",
        name: "文心一言 3.5",
        provider: "baidu",
        category: "chat",
        description: "稳定版模型",
        maxTokens: 8192,
        apiEndpoint: "https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/completions",
        apiKeyName: "ERNIE_API_KEY",
        isAvailable: true,
      },
      {
        id: "ernie-speed",
        name: "文心一言 Speed",
        provider: "baidu",
        category: "chat",
        description: "极速版模型",
        maxTokens: 8192,
        apiEndpoint: "https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/ernie_speed",
        apiKeyName: "ERNIE_API_KEY",
        isAvailable: true,
      },
      {
        id: "ernie-lite",
        name: "文心一言 Lite",
        provider: "baidu",
        category: "chat",
        description: "轻量版模型",
        maxTokens: 8192,
        apiEndpoint: "https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/ernie-lite-8k",
        apiKeyName: "ERNIE_API_KEY",
        isAvailable: true,
      },
    ],
  },
  // Mistral Models
  {
    id: "mistral",
    name: "Mistral AI",
    logo: "🌀",
    website: "https://mistral.ai",
    apiKeyName: "MISTRAL_API_KEY",
    models: [
      {
        id: "mistral-large",
        name: "Mistral Large",
        provider: "mistral",
        category: "chat",
        description: "旗舰级模型",
        maxTokens: 128000,
        apiEndpoint: "https://api.mistral.ai/v1/chat/completions",
        apiKeyName: "MISTRAL_API_KEY",
        isAvailable: true,
      },
      {
        id: "mistral-medium",
        name: "Mistral Medium",
        provider: "mistral",
        category: "chat",
        description: "平衡型模型",
        maxTokens: 32000,
        apiEndpoint: "https://api.mistral.ai/v1/chat/completions",
        apiKeyName: "MISTRAL_API_KEY",
        isAvailable: true,
      },
      {
        id: "mistral-small",
        name: "Mistral Small",
        provider: "mistral",
        category: "chat",
        description: "快速模型",
        maxTokens: 32000,
        apiEndpoint: "https://api.mistral.ai/v1/chat/completions",
        apiKeyName: "MISTRAL_API_KEY",
        isAvailable: true,
      },
      {
        id: "mistral-nemo",
        name: "Mistral Nemo",
        provider: "mistral",
        category: "chat",
        description: "高效能模型",
        maxTokens: 128000,
        apiEndpoint: "https://api.mistral.ai/v1/chat/completions",
        apiKeyName: "MISTRAL_API_KEY",
        isAvailable: true,
      },
      {
        id: "codestral",
        name: "Codestral",
        provider: "mistral",
        category: "code",
        description: "代码专用模型",
        maxTokens: 32000,
        apiEndpoint: "https://api.mistral.ai/v1/chat/completions",
        apiKeyName: "MISTRAL_API_KEY",
        isAvailable: true,
      },
      {
        id: "mixtral-8x7b",
        name: "Mixtral 8x7B",
        provider: "mistral",
        category: "chat",
        description: "MoE架构模型",
        maxTokens: 32000,
        apiEndpoint: "https://api.mistral.ai/v1/chat/completions",
        apiKeyName: "MISTRAL_API_KEY",
        isAvailable: true,
      },
      {
        id: "mixtral-8x22b",
        name: "Mixtral 8x22B",
        provider: "mistral",
        category: "chat",
        description: "大型MoE模型",
        maxTokens: 64000,
        apiEndpoint: "https://api.mistral.ai/v1/chat/completions",
        apiKeyName: "MISTRAL_API_KEY",
        isAvailable: true,
      },
      {
        id: "pixtral-large",
        name: "Pixtral Large",
        provider: "mistral",
        category: "vision",
        description: "视觉语言模型",
        maxTokens: 128000,
        apiEndpoint: "https://api.mistral.ai/v1/chat/completions",
        apiKeyName: "MISTRAL_API_KEY",
        isAvailable: true,
      },
    ],
  },
  // Cohere Models
  {
    id: "cohere",
    name: "Cohere",
    logo: "💫",
    website: "https://cohere.com",
    apiKeyName: "COHERE_API_KEY",
    models: [
      {
        id: "command-r-plus",
        name: "Command R+",
        provider: "cohere",
        category: "chat",
        description: "最强大模型",
        maxTokens: 128000,
        apiEndpoint: "https://api.cohere.ai/v1/chat",
        apiKeyName: "COHERE_API_KEY",
        isAvailable: true,
      },
      {
        id: "command-r",
        name: "Command R",
        provider: "cohere",
        category: "chat",
        description: "高性能模型",
        maxTokens: 128000,
        apiEndpoint: "https://api.cohere.ai/v1/chat",
        apiKeyName: "COHERE_API_KEY",
        isAvailable: true,
      },
      {
        id: "command",
        name: "Command",
        provider: "cohere",
        category: "chat",
        description: "通用模型",
        maxTokens: 4096,
        apiEndpoint: "https://api.cohere.ai/v1/chat",
        apiKeyName: "COHERE_API_KEY",
        isAvailable: true,
      },
      {
        id: "command-light",
        name: "Command Light",
        provider: "cohere",
        category: "chat",
        description: "轻量模型",
        maxTokens: 4096,
        apiEndpoint: "https://api.cohere.ai/v1/chat",
        apiKeyName: "COHERE_API_KEY",
        isAvailable: true,
      },
      {
        id: "embed-english-v3",
        name: "Embed English V3",
        provider: "cohere",
        category: "embedding",
        description: "英文嵌入模型",
        maxTokens: 512,
        apiEndpoint: "https://api.cohere.ai/v1/embed",
        apiKeyName: "COHERE_API_KEY",
        isAvailable: true,
      },
      {
        id: "embed-multilingual-v3",
        name: "Embed Multilingual V3",
        provider: "cohere",
        category: "embedding",
        description: "多语言嵌入",
        maxTokens: 512,
        apiEndpoint: "https://api.cohere.ai/v1/embed",
        apiKeyName: "COHERE_API_KEY",
        isAvailable: true,
      },
      {
        id: "rerank-english-v3",
        name: "Rerank English V3",
        provider: "cohere",
        category: "rerank",
        description: "英文重排序",
        maxTokens: 4096,
        apiEndpoint: "https://api.cohere.ai/v1/rerank",
        apiKeyName: "COHERE_API_KEY",
        isAvailable: true,
      },
      {
        id: "rerank-multilingual-v3",
        name: "Rerank Multilingual V3",
        provider: "cohere",
        category: "rerank",
        description: "多语言重排序",
        maxTokens: 4096,
        apiEndpoint: "https://api.cohere.ai/v1/rerank",
        apiKeyName: "COHERE_API_KEY",
        isAvailable: true,
      },
    ],
  },
  // xAI/Grok Models
  {
    id: "xai",
    name: "xAI",
    logo: "https://cdn.jsdelivr.net/gh/glincker/thesvg@main/public/icons/x-ai/default.svg",
    website: "https://x.ai",
    apiKeyName: "XAI_API_KEY",
    models: [
      {
        id: "grok-2",
        name: "Grok 2",
        provider: "xai",
        category: "chat",
        description: "最新Grok模型",
        maxTokens: 128000,
        apiEndpoint: "https://api.x.ai/v1/chat/completions",
        apiKeyName: "XAI_API_KEY",
        isAvailable: true,
      },
      {
        id: "grok-2-mini",
        name: "Grok 2 Mini",
        provider: "xai",
        category: "chat",
        description: "轻量Grok模型",
        maxTokens: 128000,
        apiEndpoint: "https://api.x.ai/v1/chat/completions",
        apiKeyName: "XAI_API_KEY",
        isAvailable: true,
      },
      {
        id: "grok-beta",
        name: "Grok Beta",
        provider: "xai",
        category: "chat",
        description: "测试版模型",
        maxTokens: 128000,
        apiEndpoint: "https://api.x.ai/v1/chat/completions",
        apiKeyName: "XAI_API_KEY",
        isAvailable: true,
      },
      {
        id: "grok-vision",
        name: "Grok Vision",
        provider: "xai",
        category: "vision",
        description: "视觉理解模型",
        maxTokens: 128000,
        apiEndpoint: "https://api.x.ai/v1/chat/completions",
        apiKeyName: "XAI_API_KEY",
        isAvailable: true,
      },
    ],
  },
  // Perplexity Models
  {
    id: "perplexity",
    name: "Perplexity",
    logo: "🔍",
    website: "https://perplexity.ai",
    apiKeyName: "PERPLEXITY_API_KEY",
    models: [
      {
        id: "sonar-large",
        name: "Sonar Large",
        provider: "perplexity",
        category: "search",
        description: "大型搜索模型",
        maxTokens: 28000,
        apiEndpoint: "https://api.perplexity.ai/chat/completions",
        apiKeyName: "PERPLEXITY_API_KEY",
        isAvailable: true,
      },
      {
        id: "sonar-small",
        name: "Sonar Small",
        provider: "perplexity",
        category: "search",
        description: "小型搜索模型",
        maxTokens: 28000,
        apiEndpoint: "https://api.perplexity.ai/chat/completions",
        apiKeyName: "PERPLEXITY_API_KEY",
        isAvailable: true,
      },
      {
        id: "sonar-pro",
        name: "Sonar Pro",
        provider: "perplexity",
        category: "search",
        description: "专业搜索模型",
        maxTokens: 28000,
        apiEndpoint: "https://api.perplexity.ai/chat/completions",
        apiKeyName: "PERPLEXITY_API_KEY",
        isAvailable: true,
      },
      {
        id: "sonar-reasoning",
        name: "Sonar Reasoning",
        provider: "perplexity",
        category: "reasoning",
        description: "推理搜索模型",
        maxTokens: 28000,
        apiEndpoint: "https://api.perplexity.ai/chat/completions",
        apiKeyName: "PERPLEXITY_API_KEY",
        isAvailable: true,
      },
    ],
  },
  // Together AI Models
  {
    id: "together",
    name: "Together AI",
    logo: "🤝",
    website: "https://together.ai",
    apiKeyName: "TOGETHER_API_KEY",
    models: [
      {
        id: "nous-hermes-2-mixtral",
        name: "Nous Hermes 2 Mixtral",
        provider: "together",
        category: "chat",
        description: "高质量对话",
        maxTokens: 32768,
        apiEndpoint: "https://api.together.xyz/v1/chat/completions",
        apiKeyName: "TOGETHER_API_KEY",
        isAvailable: true,
      },
      {
        id: "qwen-72b-instruct",
        name: "Qwen 72B Instruct",
        provider: "together",
        category: "chat",
        description: "指令优化版",
        maxTokens: 32768,
        apiEndpoint: "https://api.together.xyz/v1/chat/completions",
        apiKeyName: "TOGETHER_API_KEY",
        isAvailable: true,
      },
      {
        id: "wizardlm-2-8x22b",
        name: "WizardLM 2 8x22B",
        provider: "together",
        category: "chat",
        description: "MoE对话模型",
        maxTokens: 65536,
        apiEndpoint: "https://api.together.xyz/v1/chat/completions",
        apiKeyName: "TOGETHER_API_KEY",
        isAvailable: true,
      },
      {
        id: "dbrx-instruct",
        name: "DBRX Instruct",
        provider: "together",
        category: "chat",
        description: "Databricks模型",
        maxTokens: 32768,
        apiEndpoint: "https://api.together.xyz/v1/chat/completions",
        apiKeyName: "TOGETHER_API_KEY",
        isAvailable: true,
      },
      {
        id: "yi-34b-chat",
        name: "Yi 34B Chat",
        provider: "together",
        category: "chat",
        description: "零一万物模型",
        maxTokens: 4096,
        apiEndpoint: "https://api.together.xyz/v1/chat/completions",
        apiKeyName: "TOGETHER_API_KEY",
        isAvailable: true,
      },
      {
        id: "solar-10.7b",
        name: "Solar 10.7B",
        provider: "together",
        category: "chat",
        description: "韩国模型",
        maxTokens: 4096,
        apiEndpoint: "https://api.together.xyz/v1/chat/completions",
        apiKeyName: "TOGETHER_API_KEY",
        isAvailable: true,
      },
    ],
  },
  // Groq Models
  {
    id: "groq",
    name: "Groq",
    logo: "https://cdn.jsdelivr.net/gh/glincker/thesvg@main/public/icons/groq/default.svg",
    website: "https://groq.com",
    apiKeyName: "GROQ_API_KEY",
    models: [
      {
        id: "llama-3.2-90b-vision",
        name: "Llama 3.2 90B Vision",
        provider: "groq",
        category: "vision",
        description: "超快视觉模型",
        maxTokens: 8192,
        apiEndpoint: "https://api.groq.com/openai/v1/chat/completions",
        apiKeyName: "GROQ_API_KEY",
        isAvailable: true,
      },
      {
        id: "llama-3.2-11b-vision",
        name: "Llama 3.2 11B Vision",
        provider: "groq",
        category: "vision",
        description: "快速视觉模型",
        maxTokens: 8192,
        apiEndpoint: "https://api.groq.com/openai/v1/chat/completions",
        apiKeyName: "GROQ_API_KEY",
        isAvailable: true,
      },
      {
        id: "llama-3.1-70b-versatile",
        name: "Llama 3.1 70B",
        provider: "groq",
        category: "chat",
        description: "多功能模型",
        maxTokens: 32768,
        apiEndpoint: "https://api.groq.com/openai/v1/chat/completions",
        apiKeyName: "GROQ_API_KEY",
        isAvailable: true,
      },
      {
        id: "mixtral-8x7b-groq",
        name: "Mixtral 8x7B",
        provider: "groq",
        category: "chat",
        description: "MoE快速模型",
        maxTokens: 32768,
        apiEndpoint: "https://api.groq.com/openai/v1/chat/completions",
        apiKeyName: "GROQ_API_KEY",
        isAvailable: true,
      },
      {
        id: "gemma-2-9b",
        name: "Gemma 2 9B",
        provider: "groq",
        category: "chat",
        description: "Google开源",
        maxTokens: 8192,
        apiEndpoint: "https://api.groq.com/openai/v1/chat/completions",
        apiKeyName: "GROQ_API_KEY",
        isAvailable: true,
      },
      {
        id: "whisper-large-v3",
        name: "Whisper Large V3",
        provider: "groq",
        category: "audio",
        description: "语音识别",
        maxTokens: 0,
        apiEndpoint: "https://api.groq.com/openai/v1/audio/transcriptions",
        apiKeyName: "GROQ_API_KEY",
        isAvailable: true,
      },
    ],
  },
  // Replicate Models
  {
    id: "replicate",
    name: "Replicate",
    logo: "🔄",
    website: "https://replicate.com",
    apiKeyName: "REPLICATE_API_KEY",
    models: [
      {
        id: "sdxl",
        name: "Stable Diffusion XL",
        provider: "replicate",
        category: "image",
        description: "图像生成",
        maxTokens: 0,
        apiEndpoint: "https://api.replicate.com/v1/predictions",
        apiKeyName: "REPLICATE_API_KEY",
        isAvailable: true,
      },
      {
        id: "sd3",
        name: "Stable Diffusion 3",
        provider: "replicate",
        category: "image",
        description: "最新SD模型",
        maxTokens: 0,
        apiEndpoint: "https://api.replicate.com/v1/predictions",
        apiKeyName: "REPLICATE_API_KEY",
        isAvailable: true,
      },
      {
        id: "flux-1.1-pro",
        name: "Flux 1.1 Pro",
        provider: "replicate",
        category: "image",
        description: "高质量生成",
        maxTokens: 0,
        apiEndpoint: "https://api.replicate.com/v1/predictions",
        apiKeyName: "REPLICATE_API_KEY",
        isAvailable: true,
      },
      {
        id: "flux-schnell",
        name: "Flux Schnell",
        provider: "replicate",
        category: "image",
        description: "快速生成",
        maxTokens: 0,
        apiEndpoint: "https://api.replicate.com/v1/predictions",
        apiKeyName: "REPLICATE_API_KEY",
        isAvailable: true,
      },
      {
        id: "musicgen",
        name: "MusicGen",
        provider: "replicate",
        category: "audio",
        description: "音乐生成",
        maxTokens: 0,
        apiEndpoint: "https://api.replicate.com/v1/predictions",
        apiKeyName: "REPLICATE_API_KEY",
        isAvailable: true,
      },
      {
        id: "audiocraft",
        name: "AudioCraft",
        provider: "replicate",
        category: "audio",
        description: "音频生成",
        maxTokens: 0,
        apiEndpoint: "https://api.replicate.com/v1/predictions",
        apiKeyName: "REPLICATE_API_KEY",
        isAvailable: true,
      },
      {
        id: "video-crafter",
        name: "Video Crafter",
        provider: "replicate",
        category: "video",
        description: "视频生成",
        maxTokens: 0,
        apiEndpoint: "https://api.replicate.com/v1/predictions",
        apiKeyName: "REPLICATE_API_KEY",
        isAvailable: true,
      },
    ],
  },
  // Hugging Face Models
  {
    id: "huggingface",
    name: "Hugging Face",
    logo: "🤗",
    website: "https://huggingface.co",
    apiKeyName: "HUGGINGFACE_API_KEY",
    models: [
      {
        id: "zephyr-7b",
        name: "Zephyr 7B",
        provider: "huggingface",
        category: "chat",
        description: "高效对话",
        maxTokens: 8192,
        apiEndpoint: "https://api-inference.huggingface.co/models",
        apiKeyName: "HUGGINGFACE_API_KEY",
        isAvailable: true,
      },
      {
        id: "falcon-180b",
        name: "Falcon 180B",
        provider: "huggingface",
        category: "chat",
        description: "大规模模型",
        maxTokens: 2048,
        apiEndpoint: "https://api-inference.huggingface.co/models",
        apiKeyName: "HUGGINGFACE_API_KEY",
        isAvailable: true,
      },
      {
        id: "starcoder2-15b",
        name: "StarCoder2 15B",
        provider: "huggingface",
        category: "code",
        description: "代码生成",
        maxTokens: 8192,
        apiEndpoint: "https://api-inference.huggingface.co/models",
        apiKeyName: "HUGGINGFACE_API_KEY",
        isAvailable: true,
      },
      {
        id: "codellama-instruct",
        name: "CodeLlama Instruct",
        provider: "huggingface",
        category: "code",
        description: "代码指令",
        maxTokens: 16384,
        apiEndpoint: "https://api-inference.huggingface.co/models",
        apiKeyName: "HUGGINGFACE_API_KEY",
        isAvailable: true,
      },
      {
        id: "bert-base",
        name: "BERT Base",
        provider: "huggingface",
        category: "embedding",
        description: "文本嵌入",
        maxTokens: 512,
        apiEndpoint: "https://api-inference.huggingface.co/models",
        apiKeyName: "HUGGINGFACE_API_KEY",
        isAvailable: true,
      },
      {
        id: "roberta-large",
        name: "RoBERTa Large",
        provider: "huggingface",
        category: "embedding",
        description: "增强嵌入",
        maxTokens: 512,
        apiEndpoint: "https://api-inference.huggingface.co/models",
        apiKeyName: "HUGGINGFACE_API_KEY",
        isAvailable: true,
      },
    ],
  },
  // AI21 Models
  {
    id: "ai21",
    name: "AI21 Labs",
    logo: "🧬",
    website: "https://ai21.com",
    apiKeyName: "AI21_API_KEY",
    models: [
      {
        id: "jamba-1.5-large",
        name: "Jamba 1.5 Large",
        provider: "ai21",
        category: "chat",
        description: "最新Jamba",
        maxTokens: 256000,
        apiEndpoint: "https://api.ai21.com/studio/v1/chat/completions",
        apiKeyName: "AI21_API_KEY",
        isAvailable: true,
      },
      {
        id: "jamba-1.5-mini",
        name: "Jamba 1.5 Mini",
        provider: "ai21",
        category: "chat",
        description: "轻量Jamba",
        maxTokens: 256000,
        apiEndpoint: "https://api.ai21.com/studio/v1/chat/completions",
        apiKeyName: "AI21_API_KEY",
        isAvailable: true,
      },
      {
        id: "jurassic-2-ultra",
        name: "Jurassic-2 Ultra",
        provider: "ai21",
        category: "chat",
        description: "旗舰模型",
        maxTokens: 8192,
        apiEndpoint: "https://api.ai21.com/studio/v1/chat/completions",
        apiKeyName: "AI21_API_KEY",
        isAvailable: true,
      },
      {
        id: "jurassic-2-mid",
        name: "Jurassic-2 Mid",
        provider: "ai21",
        category: "chat",
        description: "平衡模型",
        maxTokens: 8192,
        apiEndpoint: "https://api.ai21.com/studio/v1/chat/completions",
        apiKeyName: "AI21_API_KEY",
        isAvailable: true,
      },
    ],
  },
  // Zhipu/GLM Models
  {
    id: "zhipu",
    name: "智谱AI",
    logo: "🔮",
    website: "https://zhipuai.cn",
    apiKeyName: "ZHIPU_API_KEY",
    models: [
      {
        id: "glm-4",
        name: "GLM-4",
        provider: "zhipu",
        category: "chat",
        description: "最新GLM模型",
        maxTokens: 128000,
        apiEndpoint: "https://open.bigmodel.cn/api/paas/v4/chat/completions",
        apiKeyName: "ZHIPU_API_KEY",
        isAvailable: true,
      },
      {
        id: "glm-4-plus",
        name: "GLM-4 Plus",
        provider: "zhipu",
        category: "chat",
        description: "增强版GLM",
        maxTokens: 128000,
        apiEndpoint: "https://open.bigmodel.cn/api/paas/v4/chat/completions",
        apiKeyName: "ZHIPU_API_KEY",
        isAvailable: true,
      },
      {
        id: "glm-4-air",
        name: "GLM-4 Air",
        provider: "zhipu",
        category: "chat",
        description: "快速版GLM",
        maxTokens: 128000,
        apiEndpoint: "https://open.bigmodel.cn/api/paas/v4/chat/completions",
        apiKeyName: "ZHIPU_API_KEY",
        isAvailable: true,
      },
      {
        id: "glm-4-flash",
        name: "GLM-4 Flash",
        provider: "zhipu",
        category: "chat",
        description: "极速版GLM",
        maxTokens: 128000,
        apiEndpoint: "https://open.bigmodel.cn/api/paas/v4/chat/completions",
        apiKeyName: "ZHIPU_API_KEY",
        isAvailable: true,
      },
      {
        id: "glm-4v",
        name: "GLM-4V",
        provider: "zhipu",
        category: "vision",
        description: "视觉理解",
        maxTokens: 2048,
        apiEndpoint: "https://open.bigmodel.cn/api/paas/v4/chat/completions",
        apiKeyName: "ZHIPU_API_KEY",
        isAvailable: true,
      },
      {
        id: "codegeex-4",
        name: "CodeGeeX 4",
        provider: "zhipu",
        category: "code",
        description: "代码生成",
        maxTokens: 128000,
        apiEndpoint: "https://open.bigmodel.cn/api/paas/v4/chat/completions",
        apiKeyName: "ZHIPU_API_KEY",
        isAvailable: true,
      },
    ],
  },
  // Moonshot/Kimi Models
  {
    id: "moonshot",
    name: "月之暗面",
    logo: "🌙",
    website: "https://kimi.ai",
    apiKeyName: "MOONSHOT_API_KEY",
    models: [
      {
        id: "moonshot-v1-8k",
        name: "Moonshot V1 8K",
        provider: "moonshot",
        category: "chat",
        description: "标准版Kimi",
        maxTokens: 8000,
        apiEndpoint: "https://api.moonshot.cn/v1/chat/completions",
        apiKeyName: "MOONSHOT_API_KEY",
        isAvailable: true,
      },
      {
        id: "moonshot-v1-32k",
        name: "Moonshot V1 32K",
        provider: "moonshot",
        category: "chat",
        description: "长文本版",
        maxTokens: 32000,
        apiEndpoint: "https://api.moonshot.cn/v1/chat/completions",
        apiKeyName: "MOONSHOT_API_KEY",
        isAvailable: true,
      },
      {
        id: "moonshot-v1-128k",
        name: "Moonshot V1 128K",
        provider: "moonshot",
        category: "chat",
        description: "超长文本",
        maxTokens: 128000,
        apiEndpoint: "https://api.moonshot.cn/v1/chat/completions",
        apiKeyName: "MOONSHOT_API_KEY",
        isAvailable: true,
      },
    ],
  },
  // ByteDance/Doubao Models
  {
    id: "bytedance",
    name: "字节跳动",
    logo: "🎵",
    website: "https://doubao.ai",
    apiKeyName: "DOUBAO_API_KEY",
    models: [
      {
        id: "doubao-pro-32k",
        name: "豆包 Pro 32K",
        provider: "bytedance",
        category: "chat",
        description: "专业版豆包",
        maxTokens: 32000,
        apiEndpoint: "https://ark.cn-beijing.volces.com/api/v3/chat/completions",
        apiKeyName: "DOUBAO_API_KEY",
        isAvailable: true,
      },
      {
        id: "doubao-pro-128k",
        name: "豆包 Pro 128K",
        provider: "bytedance",
        category: "chat",
        description: "长文本版",
        maxTokens: 128000,
        apiEndpoint: "https://ark.cn-beijing.volces.com/api/v3/chat/completions",
        apiKeyName: "DOUBAO_API_KEY",
        isAvailable: true,
      },
      {
        id: "doubao-lite-32k",
        name: "豆包 Lite 32K",
        provider: "bytedance",
        category: "chat",
        description: "轻量版",
        maxTokens: 32000,
        apiEndpoint: "https://ark.cn-beijing.volces.com/api/v3/chat/completions",
        apiKeyName: "DOUBAO_API_KEY",
        isAvailable: true,
      },
      {
        id: "doubao-vision",
        name: "豆包 Vision",
        provider: "bytedance",
        category: "vision",
        description: "视觉理解",
        maxTokens: 4096,
        apiEndpoint: "https://ark.cn-beijing.volces.com/api/v3/chat/completions",
        apiKeyName: "DOUBAO_API_KEY",
        isAvailable: true,
      },
    ],
  },
  // Microsoft Copilot
  {
    id: "microsoft",
    name: "Microsoft",
    logo: "🪟",
    website: "https://copilot.microsoft.com",
    apiKeyName: "AZURE_API_KEY",
    models: [
      {
        id: "copilot-gpt4",
        name: "Copilot GPT-4",
        provider: "microsoft",
        category: "chat",
        description: "Azure GPT-4",
        maxTokens: 128000,
        apiEndpoint: "https://api.openai.azure.com/openai/deployments",
        apiKeyName: "AZURE_API_KEY",
        isAvailable: true,
      },
      {
        id: "copilot-gpt4-turbo",
        name: "Copilot GPT-4 Turbo",
        provider: "microsoft",
        category: "chat",
        description: "Azure Turbo",
        maxTokens: 128000,
        apiEndpoint: "https://api.openai.azure.com/openai/deployments",
        apiKeyName: "AZURE_API_KEY",
        isAvailable: true,
      },
      {
        id: "phi-3-medium",
        name: "Phi-3 Medium",
        provider: "microsoft",
        category: "chat",
        description: "微软小模型",
        maxTokens: 128000,
        apiEndpoint: "https://api.openai.azure.com/openai/deployments",
        apiKeyName: "AZURE_API_KEY",
        isAvailable: true,
      },
      {
        id: "phi-3-mini",
        name: "Phi-3 Mini",
        provider: "microsoft",
        category: "chat",
        description: "超轻量模型",
        maxTokens: 128000,
        apiEndpoint: "https://api.openai.azure.com/openai/deployments",
        apiKeyName: "AZURE_API_KEY",
        isAvailable: true,
      },
    ],
  },
  // Stability AI Models
  {
    id: "stability",
    name: "Stability AI",
    logo: "🎨",
    website: "https://stability.ai",
    apiKeyName: "STABILITY_API_KEY",
    models: [
      {
        id: "stable-diffusion-3",
        name: "Stable Diffusion 3",
        provider: "stability",
        category: "image",
        description: "最新SD模型",
        maxTokens: 0,
        apiEndpoint: "https://api.stability.ai/v2beta/stable-image/generate",
        apiKeyName: "STABILITY_API_KEY",
        isAvailable: true,
      },
      {
        id: "sd3-turbo",
        name: "SD3 Turbo",
        provider: "stability",
        category: "image",
        description: "快速生成",
        maxTokens: 0,
        apiEndpoint: "https://api.stability.ai/v2beta/stable-image/generate",
        apiKeyName: "STABILITY_API_KEY",
        isAvailable: true,
      },
      {
        id: "stable-image-ultra",
        name: "Stable Image Ultra",
        provider: "stability",
        category: "image",
        description: "超高质量",
        maxTokens: 0,
        apiEndpoint: "https://api.stability.ai/v2beta/stable-image/generate",
        apiKeyName: "STABILITY_API_KEY",
        isAvailable: true,
      },
      {
        id: "stable-video-diffusion",
        name: "Stable Video",
        provider: "stability",
        category: "video",
        description: "视频生成",
        maxTokens: 0,
        apiEndpoint: "https://api.stability.ai/v2beta/video",
        apiKeyName: "STABILITY_API_KEY",
        isAvailable: true,
      },
      {
        id: "stable-audio",
        name: "Stable Audio",
        provider: "stability",
        category: "audio",
        description: "音频生成",
        maxTokens: 0,
        apiEndpoint: "https://api.stability.ai/v2beta/audio",
        apiKeyName: "STABILITY_API_KEY",
        isAvailable: true,
      },
    ],
  },
  // Midjourney
  {
    id: "midjourney",
    name: "Midjourney",
    logo: "🌌",
    website: "https://midjourney.com",
    apiKeyName: "MIDJOURNEY_API_KEY",
    models: [
      {
        id: "mj-v6",
        name: "Midjourney V6",
        provider: "midjourney",
        category: "image",
        description: "最新版本",
        maxTokens: 0,
        apiEndpoint: "https://api.midjourney.com",
        apiKeyName: "MIDJOURNEY_API_KEY",
        isAvailable: true,
      },
      {
        id: "mj-v5.2",
        name: "Midjourney V5.2",
        provider: "midjourney",
        category: "image",
        description: "稳定版本",
        maxTokens: 0,
        apiEndpoint: "https://api.midjourney.com",
        apiKeyName: "MIDJOURNEY_API_KEY",
        isAvailable: true,
      },
      {
        id: "niji-6",
        name: "Niji 6",
        provider: "midjourney",
        category: "image",
        description: "动漫风格",
        maxTokens: 0,
        apiEndpoint: "https://api.midjourney.com",
        apiKeyName: "MIDJOURNEY_API_KEY",
        isAvailable: true,
      },
    ],
  },
]

export function getAllModels(): AIModel[] {
  return AI_PROVIDERS.flatMap((provider) => provider.models)
}

export function getModelsByCategory(category: string): AIModel[] {
  return getAllModels().filter((model) => model.category === category)
}

export function getModelsByProvider(providerId: string): AIModel[] {
  const provider = AI_PROVIDERS.find((p) => p.id === providerId)
  return provider?.models || []
}

export function getModelById(modelId: string): AIModel | undefined {
  return getAllModels().find((model) => model.id === modelId)
}

export function getProviderById(providerId: string): AIProvider | undefined {
  return AI_PROVIDERS.find((p) => p.id === providerId)
}

export const MODEL_CATEGORIES = [
  { id: "chat", name: "对话", icon: "💬" },
  { id: "code", name: "代码", icon: "💻" },
  { id: "vision", name: "视觉", icon: "👁️" },
  { id: "image", name: "图像生成", icon: "🎨" },
  { id: "audio", name: "音频", icon: "🎵" },
  { id: "video", name: "视频", icon: "🎬" },
  { id: "embedding", name: "嵌入", icon: "📊" },
  { id: "reasoning", name: "推理", icon: "🧠" },
  { id: "search", name: "搜索", icon: "🔍" },
  { id: "math", name: "数学", icon: "🔢" },
  { id: "rerank", name: "重排序", icon: "📋" },
]

// Total models count
export const TOTAL_MODELS_COUNT = getAllModels().length
